title = "Bunyan Home"
baseURL = "https://bunyanhome.com/"
languageCode = "en-us"
disableHugoGeneratorInject = true

[imaging]
  quality = 85
  resampleFilter = "Lanczos"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
parallelism = 1
